language: node_js
node_js:
  - '7'
  - '8'
  - '9'
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
  - yarn run build
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run test
  - yarn run check
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: OYbvzjzU/wHUh2Fku1ND8XkXNF6cgRSwbcad1YZDEHjFyzA82c5Ozyu9wRx0bu7DR9ka34wXiSFsrk0ui0zWsVnApmg4PY1hHyGWhwKLz3snPWlkNorUGK3A5JCdtUVTJWAdAliOEIvEou6i6RQUInU8KoQOiogTtFz5CkAVhuZX5+Q2noB3r9MEYv/g3Lus++Jrf9LEiE7iHF40FfKvH05TcdmLbIuE63Bd29URI+SLuz9mT0hOxyHGXo9RRKIeogEOwiXk4Z93AlP3CdQX7gol0iMVdx9GC0yVB1EMBFbUb5HjC64OLPCQ6OwSzCNl0OOhGdCJlWisFfU5TblfzlgQ3r8vZI/PW6vvCyvltMuBizJTP32l/OQHGam5Zt5fsrW5euQQ/NewF2nIYHCLk3iU+c1ZCZ1VnuSsO94eDlNN2dyObb+GWnnDW7D9fFZEfWHk8yB7ZP/A85ks/E8Adp3k9CQl93Pk+VR5OrLjgqAEaIi3WNtjg27+U2RNDy0eBI6WieVB3RCjYeHDdn/XpQJFdSSp/tqrkd4oSFqsT4/ZPNIrJQScRg4OsNXKVYK7ASjqjDXBB0e47V0p1jz5jNXm8VoVcHl6YxUTrgEvFJv5L98cqYAq8xoszGKV08IyDF3gkG6ulxTMOUJH9yWUWkP7QJhNLrj1aBsTQraIx+U=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 9
env:
  global:
    - secure: BtWq0vnVbfQFR7B2DBhI4QUni/yQz4kjkL4n76w82CxrzTCEJJQYrARZSAjO3eoyoj5fL7aK47qQFZaRW6hm0Z/t9T3YwAYS4oRm1+/ePYqoAf8H3LnJP1wbUpemFIjkgGKQ/nOqMmhsi0YjzMO30+r+YqfRQTSdKxG4v5IEYoa5KlQbTcD6PDcegGuYVm5H8XiP5Z0q0t9DgFPd7NMWDmD1CYJGlALH/ORf4U6BmmM7gwtCLPpyP1OIQyz3ybN1EiakY2fn/08d39j21F4a6bagdGq7bnPby2b0HN0pBaiSRpwf1F9AizDpbHPGshypk4buVcsJSsOnl7kSlcuFCjQJestO3RDs3IIpt4RwW/GwWBwTz/6IVCYwHeCVNQlUgS0XWVE9UC9nW5NYF2F2t4AiqglS35kzNaFLt8eYhqpnOJNxNQI1JFQhHh5IxCihEuFG64VXl1ZAEHoOw9UCa6eiwlFhWVmA8gABgHvyW2jqf/66G9iHYdRzsRDvu1ThlFdqrr14BmTRY1KlrKTIGydLGhMtQAB8WTCUlhC586GBiZ8NgvuDKT9MX/iUpwGi8VzNwxcUpG5YkAhbkYsxdDNkZ0hlYGiE4Zwm4SOAU0KptMLDMh4OLYRkyUqPO0/8Bc/EenoJ7lhFJ/xCmgkoIpCFQfAcQ03rAZPZAsyk47o=
    - secure: Ugcvy60xS+L/aan1zFoJDrgpsYEQcc+1hZce8nXon19FrbKymooXVlvrkAy0sRxrcsNBUpTG6jIKikAxsHAAsM/kP5J8WKV5Duu70RnAP+uMoJcgNnzJtu5qEAobxZ3VRCWfB4G+lDYkOxKqcob7wrkeGrEqrbC344BY0BrXHWcGk+gY/EiuWMDruDFZFPuksD7FV4y1h+qcCx5Yto1NhHJ3vZXIYpy2Kqrnkr/OKHg53N8S9R45eLzNFNse/h5ja2GzVrwVkBNNX2XnYXl/F61dnQ+v7UzInMJcBgifHleY7Ps3wKsc+gLEYJydhCZD/YAHdizdZFIxYjytFscHKrMMozbkCdOVzsBfN0i0LzOrVDhrX1lpfJ0Yh/Ly0oI7AZg+C87IMWNeg/vTsqhUIcIi61TWoAIx8J+RW7DrMSEs5rrTDipHwRez1zrG6hJBj8WSSYa+mC2rk2HcPa1Jv+jod+/uk3/F2Bdck1vaiW2gIluSAlWwMJq6cOMlJJwlhQArZMYg4hgYUpJ5x1oYMOIX+pNukCDufRkepDo5ASfx5rIyWEi4cgVnjmXGZlyRi1+Mus2YqB7GQ4air2nj0CUuDg5CTcZ4KYHpDBARDxKnZMTqCm9n4WN2w59eniHJIUTyD8F0jue9V76foI3z0KUg+hWOgyIlCejN8lYUGUQ=
