language: node_js
node_js:
  - '13'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run build
  - yarn run lint
  - yarn run test
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: OYbvzjzU/wHUh2Fku1ND8XkXNF6cgRSwbcad1YZDEHjFyzA82c5Ozyu9wRx0bu7DR9ka34wXiSFsrk0ui0zWsVnApmg4PY1hHyGWhwKLz3snPWlkNorUGK3A5JCdtUVTJWAdAliOEIvEou6i6RQUInU8KoQOiogTtFz5CkAVhuZX5+Q2noB3r9MEYv/g3Lus++Jrf9LEiE7iHF40FfKvH05TcdmLbIuE63Bd29URI+SLuz9mT0hOxyHGXo9RRKIeogEOwiXk4Z93AlP3CdQX7gol0iMVdx9GC0yVB1EMBFbUb5HjC64OLPCQ6OwSzCNl0OOhGdCJlWisFfU5TblfzlgQ3r8vZI/PW6vvCyvltMuBizJTP32l/OQHGam5Zt5fsrW5euQQ/NewF2nIYHCLk3iU+c1ZCZ1VnuSsO94eDlNN2dyObb+GWnnDW7D9fFZEfWHk8yB7ZP/A85ks/E8Adp3k9CQl93Pk+VR5OrLjgqAEaIi3WNtjg27+U2RNDy0eBI6WieVB3RCjYeHDdn/XpQJFdSSp/tqrkd4oSFqsT4/ZPNIrJQScRg4OsNXKVYK7ASjqjDXBB0e47V0p1jz5jNXm8VoVcHl6YxUTrgEvFJv5L98cqYAq8xoszGKV08IyDF3gkG6ulxTMOUJH9yWUWkP7QJhNLrj1aBsTQraIx+U=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
notifications:
  slack:
    secure: MeMFT9uhC2UdzZaEjXiloK/yHRlB2Q5k5/gPbxmJim09v7bzu0dEdusNpWuwbZJY13KXF+pXh1UPa1ICuI/GogQ7+waUldsTE7qCWDxyOAPsZIffPvJLlX4Xnkcod/QaJL1xmb9lgqxMy1jUh0gI3qGmqQ5ZQpWTkQtlnoSoQvJd3FqA1MqVl2WvzUq4ok6rAfM29oX1oVGY3Eo/pvaCms0EyL5HZzYSTYe3mUt1lagT7W2pg9IaEyf1rgHIoReoIsL9RRsu2Luj1XJd4rR1+kR3G3ndmcs5s6XtJK+XpworMEwDjSb1y+gl2FQAhwzqvGW+A7k2u7smENtp9r8qr42T7hVB5hRj4IVnuV3VRG/TLGtQ5YTdMKzV4+IUOfXlZtKKTKxhTG36E1nlSaXs9HQcHwbCguPjYf2wDdDoe5GcaJubStCWVCVgBATg5/A7dUfbTaFfxksVNPNy7yID9n04L8N0kyHljaWOs6VHLnIoTNWRRRitsRBaydwMtIZB6ikijSwqp1WSwKvB8mHCpktB4IWLhhURRtIVY7SP/efHXwIMSM25izOKmRneLIJjiTGxNSAgWvmOTWYAgVEofsXGHEvgQPIqAx177cHv6oWJHS4WpxJACsXarMzwDzHeEbfUPelOc6Vae+zuphtnbsjHfp+pePuZk0w1NEDVJwc=
