name: Test package
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      # prepare
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # test
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test
