name: Test package
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      # prepare
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # test
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test
